<a href="https://colab.research.google.com/github/pranavchat14/torch/blob/main/torch_gather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2D Case

In [1]:
import torch

In [2]:
src_2d = torch.tensor([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(src_2d)
print('Shape:', src_2d.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape: torch.Size([4, 4])



We'd like a row like output tensor of shape (1,4), so our index tensor should be of shape (1, 4) just like output tensor.

In [3]:
ind_2d = torch.tensor([3, 2, 0, 1])
ind_2d = ind_2d.reshape(1, 4)
print(ind_2d)
print('Shape:', ind_2d.shape)

tensor([[3, 2, 0, 1]])
Shape: torch.Size([1, 4])


In [4]:
print('for dim = 0', torch.gather(src_2d, 0, ind_2d))    #dim = 0, we're selecting rows a/c ind tensor.
print('for dim = 1', torch.gather(src_2d, 1, ind_2d))    #dim = 1, we're selecting columns a/c ind tensor.

for dim = 0 tensor([[12,  9,  2,  7]])
for dim = 1 tensor([[3, 2, 0, 1]])


We'd like a **column** like output tensor of shape (4,1), so our index tensor should be of shape (4, 1) just like output tensor.

In [5]:
ind_2d = torch.tensor([0, 1, 2, 3])
ind_2d = ind_2d.reshape(4, 1)
print(ind_2d)
print('Shape:', ind_2d.shape)

tensor([[0],
        [1],
        [2],
        [3]])
Shape: torch.Size([4, 1])


In [6]:
print('for dim = 0') 
print(torch.gather(src_2d, 0, ind_2d))
print('for dim = 1')
print(torch.gather(src_2d, 1, ind_2d))

for dim = 0
tensor([[ 0],
        [ 4],
        [ 8],
        [12]])
for dim = 1
tensor([[ 0],
        [ 5],
        [10],
        [15]])


# 3D Case

In [7]:
src_3d = torch.tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
                 [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]],
                  [[24, 25, 26, 27], [28, 29, 30, 31], [32, 33, 34, 35]]])
print(src_3d)
print('Shape:', src_3d.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])
Shape: torch.Size([3, 3, 4])


We'd like to have an output tensor that contains **three images(say) of row like tensor**. So the of output tensor would be (3, 1, 3) and index tensor would also have the same shape.

In [8]:
ind_3d = torch.tensor([[0, 1, 2, 2], [0, 0, 1, 2], [2, 1, 0, 2]])
ind_3d = ind_3d.reshape(3, 1, 4)
print(ind_3d)
print('Shape', ind_3d.shape)

tensor([[[0, 1, 2, 2]],

        [[0, 0, 1, 2]],

        [[2, 1, 0, 2]]])
Shape torch.Size([3, 1, 4])


In [9]:
#for dim = 0 
torch.gather(src_3d, 0, ind_3d)

tensor([[[ 0, 13, 26, 27]],

        [[ 0,  1, 14, 27]],

        [[24, 13,  2, 27]]])

In [10]:
#for dim = 1
torch.gather(src_3d, 1, ind_3d)

tensor([[[ 0,  5, 10, 11]],

        [[12, 13, 18, 23]],

        [[32, 29, 26, 35]]])

In [11]:
#for dim = 2
torch.gather(src_3d, 2, ind_3d)

tensor([[[ 0,  1,  2,  2]],

        [[12, 12, 13, 14]],

        [[26, 25, 24, 26]]])

We'd like to have an output tensor that contains **three images(say) of column like tensor**. So the of output tensor would be (3, 3, 1) and index tensor would also have the same shape.

In [12]:
ind_3d = torch.tensor([[0, 1, 2], [0, 1, 2], [0, 1, 2]])
ind_3d = ind_3d.reshape(3, 3, 1)
print(ind_3d)
print('Shape', ind_3d.shape)

tensor([[[0],
         [1],
         [2]],

        [[0],
         [1],
         [2]],

        [[0],
         [1],
         [2]]])
Shape torch.Size([3, 3, 1])


In [13]:
#for dim = 0 
torch.gather(src_3d, 0, ind_3d)

tensor([[[ 0],
         [16],
         [32]],

        [[ 0],
         [16],
         [32]],

        [[ 0],
         [16],
         [32]]])

In [14]:
#for dim = 1
torch.gather(src_3d, 1, ind_3d)

tensor([[[ 0],
         [ 4],
         [ 8]],

        [[12],
         [16],
         [20]],

        [[24],
         [28],
         [32]]])

In [15]:
#for dim = 2
torch.gather(src_3d, 2, ind_3d)

tensor([[[ 0],
         [ 5],
         [10]],

        [[12],
         [17],
         [22]],

        [[24],
         [29],
         [34]]])

We'd like to have an output tensor that contains **one image(say) of (3,3) matrix i.e, 3 rows and 3 columns**. So the of output tensor would be (1, 3, 3) and index tensor would also have the same shape.

In [16]:
ind_3d = torch.tensor([[0, 1, 2], [0, 1, 2], [0, 1, 2]])
ind_3d = ind_3d.reshape(1, 3, 3)
print(ind_3d)
print('Shape', ind_3d.shape)

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])
Shape torch.Size([1, 3, 3])


In [17]:
#for dim = 0 
torch.gather(src_3d, 0, ind_3d)

tensor([[[ 0, 13, 26],
         [ 4, 17, 30],
         [ 8, 21, 34]]])

In [18]:
#for dim = 1
torch.gather(src_3d, 1, ind_3d)

tensor([[[ 0,  5, 10],
         [ 0,  5, 10],
         [ 0,  5, 10]]])

In [19]:
#for dim = 2
torch.gather(src_3d, 2, ind_3d)

tensor([[[ 0,  1,  2],
         [ 4,  5,  6],
         [ 8,  9, 10]]])